apiVersion: v1
kind: Pod
metadata:
  name: postgres-app-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
sepc:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432

