apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    name: redis-pod
    app: demo-voting-app
sepc:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379

